modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"

[[mods]]
modId="lwsk"
version="0.0.1"
displayName="LWSK Adventures Mod"
credits="LWSK Adventures made by Incredible Games Corporation"
displayURL="https://www.patreon.com/incredible_games_corporation?fan_landing=true"
authors="IGC, InviziGamer"
description='''
LWSK Adventures is a Map and Mod that comes with a bunch of missions with puzzles, infiltration, war scenaries, and much more...
'''

[[dependencies.lwsk]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




